{{- range .Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: "{{ .syncWave | default 1 }}"
    {{- if .annotations }}
{{ .annotations | toYaml | indent 4 }}
    {{- end }}
spec:
  {{- if .ttlSecondsAfterFinished }}
  ttlSecondsAfterFinished: {{ .ttlSecondsAfterFinished }}
  {{- else }}
  ttlSecondsAfterFinished: 300
  {{- end }}
  {{- if .backoffLimit }}
  backoffLimit: {{ .backoffLimit }}
  {{- else }}
  backoffLimit: 3
  {{- end }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      {{- if $.Values.iam.service_account_name }}
      serviceAccountName: {{ $.Values.iam.service_account_name }}
      {{- end }}
      restartPolicy: {{ .restartPolicy | default "OnFailure" }}
      {{- if .nodeSelector }}
      nodeSelector:
{{ .nodeSelector | toYaml | indent 8 }}
      {{- else }}
      nodeSelector:
        node_group_type: on_demand_main
      {{- end }}
      {{- if .tolerations }}
      tolerations:
{{ .tolerations | toYaml | indent 8 }}
      {{- else }}
      tolerations:
        - key: node_group_type
          operator: Equal
          value: on_demand_main
          effect: NoSchedule
      {{- end }}
      containers:
      - name: {{ .name }}
        {{- if .image }}
        image: {{ .image }}
        {{- else }}
        image: "{{ $.Values.image.url }}/{{ $.Values.image.name }}:{{ $.Values.image.tag }}"
        {{- end }}
        imagePullPolicy: {{ .imagePullPolicy | default "Always" }}
        {{- if .command }}
        command:
{{ .command | toYaml | indent 10 }}
        {{- end }}
        {{- if .args }}
        args:
{{ .args | toYaml | indent 10 }}
        {{- end }}
        {{- if .resources }}
        resources:
{{ .resources | toYaml | indent 10 }}
        {{- else }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
        {{- end }}
        {{- if .env }}
        env:
{{ .env | toYaml | indent 10 }}
        {{- end }}
        {{- if or .envFrom $.Values.app.secretName $.Values.app.distSecretName }}
        envFrom:
        {{- if .envFrom }}
{{ .envFrom | toYaml | indent 10 }}
        {{- end }}
        {{- if $.Values.app.distSecretName }}
          - secretRef:
              name: {{ $.Values.app.distSecretName }}
        {{- end }}
        {{- if $.Values.app.secretName }}
          - secretRef:
              name: {{ $.Values.app.secretName }}
        {{- end }}
        {{- end }}
{{- end }}